title: "TransGuide UK"
description: "A clear, factual guidance for trans people in the UK"

url: "https://emma-on-github.github.io/transguide-uk"

theme: jekyll-theme-cayman

search_enabled: true

plugins:
  - jekyll-theme-cayman
